# Generated by Django 5.1.6 on 2025-06-26 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0005_comment_is_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='release_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Waktu Rilis'),
        ),
    ]
