# Generated by Django 5.1.6 on 2025-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0007_coursecontent_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=100, verbose_name='Kuota Maksimal'),
        ),
    ]
